include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
 

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
