name: ariannapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flex_color_scheme: ^7.3.1
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.1
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_app_check: ^0.3.2+2
  firebase_auth: ^5.4.2
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/horoscope/
