// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSS5HHyrdyXQGiefNdkmxMfx3p0QXOSqc',
    appId: '1:826811037308:web:fd40d4b12cd1208d40fbf9',
    messagingSenderId: '826811037308',
    projectId: 'ariannapp-sbubu',
    authDomain: 'ariannapp-sbubu.firebaseapp.com',
    storageBucket: 'ariannapp-sbubu.firebasestorage.app',
    measurementId: 'G-M96HT9FRBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0tuq1wmGVjbeVeGdnPpS6voMdDw6DWbQ',
    appId: '1:826811037308:android:12e541f86983d01840fbf9',
    messagingSenderId: '826811037308',
    projectId: 'ariannapp-sbubu',
    storageBucket: 'ariannapp-sbubu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVyPcXZRD71-OLQg-wl6DeHMWDlTOOeg',
    appId: '1:826811037308:ios:2c6feaa8c3e102c040fbf9',
    messagingSenderId: '826811037308',
    projectId: 'ariannapp-sbubu',
    storageBucket: 'ariannapp-sbubu.firebasestorage.app',
    iosBundleId: 'it.menghinidev.ariannapp',
  );

}