name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          architecture: x64
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          baseHref: /ariannapp/
          customArgs: --dart-define "MODE=lite"